version: '3'

services:

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=cleanarch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - custom

  stubby4j:
    image: sandokandias/stubby4j-docker
    ports:
      - "8882:8882"
    environment:
      STUBBY_PORT: 8882
    volumes:
      - ./data/stubby/integrations.yml:/usr/local/stubby.yml
    networks:
      - custom

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.165.70.0/16
